# Generated by Django 5.0.2 on 2024-02-08 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Rooms", "0002_remove_rooms_posts_remove_rooms_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="roomsettings",
        ),
        migrations.RemoveField(
            model_name="room",
            name="setup",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="last_edited_data",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="creation_date",
            new_name="last_edited_on",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="updated_date",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="creation_date",
            new_name="updated",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="topic",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="post",
            name="replies",
        ),
        migrations.RemoveField(
            model_name="room",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="room",
            name="posts",
        ),
        migrations.RemoveField(
            model_name="room",
            name="status",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="description",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="updated_date",
        ),
        migrations.AddField(
            model_name="post",
            name="room",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Rooms.room",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="host",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Rooms.topic",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Participant",
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
