# Generated by Django 5.0.2 on 2024-02-08 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Rooms", "0004_alter_room_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="topic",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Rooms.topic",
            ),
            preserve_default=False,
        ),
    ]
