# Generated by Django 5.0.2 on 2024-02-11 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Rooms", "0009_alter_room_options_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-updated_on", "-created_on"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="last_edited_on",
            new_name="updated_on",
        ),
    ]
